name: Publish to AUR

on:
  push:
    branches: [main]
    paths:
      - 'PKGBUILD'
      - '.SRCINFO'

jobs:
  aur:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH key for AUR
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AUR_SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          cat >> ~/.ssh/config <<EOF
          Host aur.archlinux.org
            User aur
            IdentityFile ~/.ssh/id_ed25519
            IdentitiesOnly yes
            StrictHostKeyChecking no
            UserKnownHostsFile=/dev/null
          EOF

      - name: Push to AUR
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git clone --depth=1 ssh://aur@aur.archlinux.org/terminalwrap.git aur-repo
          cp PKGBUILD .SRCINFO aur-repo/
          cd aur-repo
          git add PKGBUILD .SRCINFO
          git commit -m "Update from GitHub Actions" || true
          git push
