name: Publish to AUR

on:
  push:
    branches: [main]
    paths:
      - 'PKGBUILD'
      - '.SRCINFO'

jobs:
  aur:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AUR_SSH_PRIVATE_KEY }}" > ~/.ssh/aur
          chmod 600 ~/.ssh/aur
          echo "Host aur.archlinux.org\n  IdentityFile ~/.ssh/aur\n  User aur\n  StrictHostKeyChecking no" >> ~/.ssh/config

      - name: Push PKGBUILD and .SRCINFO to AUR
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git clone --depth=1 ssh://aur@aur.archlinux.org/terminalwrap.git aur-repo
          cp PKGBUILD .SRCINFO aur-repo/
          cd aur-repo
          git add PKGBUILD .SRCINFO
          git commit -m "Update from GitHub Actions" || echo "No changes to commit"
          git push